## Exercise 1: Convert a list and tuple into arrays

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


## Also try np.asarray for the problem above! 

In [2]:
import numpy as np

In [3]:
from numpy import array

In [17]:
list1=[1,2,3,4,5,6,7,8]
array1 = np.array((list1))
print("List to array: ")
print(array1)
print(np.asarray(list1))
tuple1=([8,4,6],[1,2,3])
array1 = np.array((tuple1))
print("Tuple to array: ")
print(array2)
print(np.asarray(tuple1))






List to array: 
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]
[[8 4 6]
 [1 2 3]]


## Exercise 2:  Convert the values of Centigrade degrees into Fahrenheit degrees

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [21]:
celsval =[-17.77777778,-11.11111111,7.33888889,1.11111111,37.72777778]
carr = np.array((celsval))
print("Values in  Centigrade degrees:")
print(carr)
print(celsval * 9 / 5 + 32)
print("Values in Fahrenheit degrees:")
print(carr)








Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


TypeError: unsupported operand type(s) for /: 'list' and 'int'

## Exercise 3: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


In [23]:
list1=[1,2,3,4,5,6,7,8]
a1 = np.array((list1))
print("Size of the array- ", a1.size)
print("Length of one array element in bytes- ", a1.itemsize)
print("Total bytes consumed by elements of the array-", a1.nbytes)




Size of the array-  8
Length of one array element in bytes-  4
Total bytes consumed by elements of the array- 32


## Exercise 4: Get the unique elements of an array

In [27]:
arr1d = np.array([10,10,20,20,30,30])
print("Original array:", arr1d)
uval1 = np.unique(arr1d)
print("Unique elements in array:", uval1)
arr2d = np.array([[1,1],[2,3]])
print("Original array:", arr2d)
uval2 = np.unique(arr2d)
print("Unique elements in array:", uval2)








Original array: [10 10 20 20 30 30]
Unique elements in array: [10 20 30]
Original array: [[1 1]
 [2 3]]
Unique elements in array: [1 2 3]


## Exercise 5: Change the dimension of an array


Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
arrn1 = np.array([1,2,3,4,5,6,7,8,9])
arrn1.shape
print("Original array:", arrn1)
arrn1.reshape(3,3)



Original array: [1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Exercise 6: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [31]:
a1 = np.linspace(2.5, 6.5, 30)
print(a1)


[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 7: Convert 1-D arrays as columns into a 2-D array

Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


In [46]:
c1 = np.array([1,2,3])
c2 = np.array([4,5,6])
c3 = np.hstack((c1, c2))
c4 = np.vstack((c1, c2))
c5 = np.column_stack((c1, c2))
print("Array1:",c1)
print("Array2:",c2)
print("Hstack:",c3)
print("Vstack:",c4)
print("Cstack:",c5)









Array1: [1 2 3]
Array2: [4 5 6]
Hstack: [1 2 3 4 5 6]
Vstack: [[1 2 3]
 [4 5 6]]
Cstack: [[1 4]
 [2 5]
 [3 6]]


## Exercise 8: Create a 5x5 matrix with row values ranging from 0 to 4

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [72]:
d1=np.zeros((5,5))
print("Original Array:",d1)
d1 = d1 + np.arange(5)
print("Row values ranging from 0 to 4:",d1)




Original Array: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4: [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 9: Sum of all the multiples of 3 or 5 below 100

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [91]:
x = np.arange(1, 100)
sum = 0
for i in x:
    if (i % 3 == 0) | (i % 5 == 0):
        print(i)
        sum = sum + i
print("Sum of multiples of 3 or 5:")
print(sum)
    
    

3
5
6
9
10
12
15
18
20
21
24
25
27
30
33
35
36
39
40
42
45
48
50
51
54
55
57
60
63
65
66
69
70
72
75
78
80
81
84
85
87
90
93
95
96
99
Sum of multiples of 3 or 5:
2318


## Exercise 10: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [28]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


In [96]:
x = np.arange(4)
print("One dimensional array:")
print(x)
y = np.arange(4)
y = np.arange(8).reshape(2,4)
print("Two dimensional array:")
print(y)
for a, b in np.nditer([x,y]):
    print("%d:%d" % (a,b),)



One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Exercise 11: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 12: Add a new row to an empty numpy array

In [116]:
s1 = np.array([])
s1 = np.append(s1, np.array([[10, 20, 30],[40,50,60]]))
s1.reshape(2,3)





array([[10., 20., 30.],
       [40., 50., 60.]])

## Exercise 13: Write a NumPy program to join a sequence of arrays along a new axis. 

In [4]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
print("Original array:")
print(a)
print(b)
z = np.vstack((a, b))
print("Sequence of arrays along a new axis:")
print(z)


Original array:
[[1]
 [2]
 [3]]
[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
